# Generated by Django 3.1.5 on 2021-02-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0003_auto_20210226_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='prize',
            field=models.IntegerField(),
        ),
    ]
