# Generated by Django 3.1.5 on 2021-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinfo', '0005_auto_20210226_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
